name: yellow_flowers
description: "App diaria con foto de flores amarillas y canción random de Spotify."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.13.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.1
  flutter_local_notifications: ^22.3.1
  permission_handler: ^11.3.1
  timezone: ^0.11.1
  flutter_timezone: ^4.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/flowers/
